blueprint:
  name: SGDevice - Plejd WPH-01 Double
  description: |
    Blueprint to integrate the Plejd WPH-01 (double rocker) with Home Assistant.

    Button mapping (clockwise IDs):
      1 = left up
      2 = right up
      3 = left down
      4 = right down

    Default behavior (when no override action is provided):
      - Up: activate scene "scene.'area_friendly_name'_home" for the configured side
      - Down: if any light in that area is on, turn off lights in that area; otherwise activate "scene.'area_friendly_name'_dim"

    Any press actions:
      - You can run extra actions on any press (any button), or per side (left/right), before the button-specific actions.
      - This is useful for things like toggling an input_boolean "deactivate motion lights", disabling/enabling other automations, etc.

    Double click:
      - Optional and disabled by default.
      - When enabled, this blueprint adds an intentional delay before running actions so it can decide between single and double click.
      - Detection is best-effort and may vary depending on the integration/event timing.

    IMPORTANT:
      - This blueprint identifies buttons by the event entity_id suffixes (_2, _3, _4).
      - Do not rename these event entities in Home Assistant, or make sure the suffixes are preserved.

    Note: This blueprint relies on the hass-plejd integration to create event entities for the button presses. Right now the trigger is based on state_changed events from these entities, which is not ideal. There are no dedicated event entities in hass-plejd yet as far as I can tell.

  domain: automation
  source_url: https://github.com/sondregronas/hass-blueprints/blob/main/devices/Plejd%20WPH-01%20Double.yaml

  input:
    switches:
      name: Plejd WPH-01 (double rocker)
      description: Select the Plejd WPH-01 device.
      selector:
        device:
          model: WPH-01-LC
          multiple: false

    left_area:
      name: Left area (optional)
      description: Area used by default actions for the left rocker.
      default: null
      selector:
        area: { }

    right_area:
      name: Right area (optional)
      description: Area used by default actions for the right rocker.
      default: null
      selector:
        area: { }

    any_press_actions:
      name: Any press actions
      collapsed: true
      input:
        any_press:
          name: Any press
          description: |
            Runs on any press (any button), before side-specific and button-specific actions.

            Useful for things like toggling an input_boolean "deactivate motion lights", disabling/enabling other automations, etc.
          default: [ ]
          selector:
            action: { }

        left_any_press:
          name: Left rockers - any press
          description: |
            Runs on any left-side press (button 1 or 3), before the button-specific action.

            Useful for things like toggling an input_boolean "deactivate motion lights", disabling/enabling other automations, etc.
          default: [ ]
          selector:
            action: { }

        right_any_press:
          name: Right rockers - any press
          description: |
            Runs on any right-side press (button 2 or 4), before the button-specific action.

            Useful for things like toggling an input_boolean "deactivate motion lights", disabling/enabling other automations, etc.
          default: [ ]
          selector:
            action: { }

    single_click_actions:
      name: Single click actions
      collapsed: true
      input:
        left_up_1x:
          name: Left up
          description: |
            Leave empty to run the default.

            Default: activates scene "scene.'area_friendly_name'_home" with a 1 second transition.
          default: [ ]
          selector:
            action: { }

        left_down_1x:
          name: Left down
          description: |
            Leave empty to run the default.

            Default:
            - If any light in the left area is on: turn off the lights with a 1 second transition.
            - Otherwise: activates "scene.'area_friendly_name'_dim" with a 1 second transition.
          default: [ ]
          selector:
            action: { }

        right_up_1x:
          name: Right up
          description: |
            Leave empty to run the default.

            Default: activates scene "scene.'area_friendly_name'_home" with a 1 second transition.
          default: [ ]
          selector:
            action: { }

        right_down_1x:
          name: Right down
          description: |
            Leave empty to run the default.

            Default:
            - If any light in the right area is on: turn off the lights with a 1 second transition.
            - Otherwise: activates "scene.'area_friendly_name'_dim" with a 1 second transition.
          default: [ ]
          selector:
            action: { }

    enable_double_click:
      name: Enable double click
      description: Enables best-effort double click detection. When enabled, actions are delayed.
      default: false
      selector:
        boolean: { }

    double_click_delay_ms:
      name: Double click delay (ms)
      description: |
        Only used when double click is enabled.

        Adds this delay before running actions and also defines the maximum time between clicks for a double click.
      default: 1000
      selector:
        number:
          min: 300
          max: 2000
          step: 50
          unit_of_measurement: ms
          mode: slider

    double_click_actions:
      name: Double click actions
      collapsed: true
      input:
        left_up_2x:
          name: Left up
          description: Action for left up double click. Only used when double click is enabled.
          default: [ ]
          selector:
            action: { }

        left_down_2x:
          name: Left down
          description: Action for left down double click. Only used when double click is enabled.
          default: [ ]
          selector:
            action: { }

        right_up_2x:
          name: Right up
          description: Action for right up double click. Only used when double click is enabled.
          default: [ ]
          selector:
            action: { }

        right_down_2x:
          name: Right down
          description: Action for right down double click. Only used when double click is enabled.
          default: [ ]
          selector:
            action: { }


variables:
  switches: !input switches

  device_event_entities: >
    {{ device_entities(switches)
       | select('match', '^event\\.')
       | list }}

  left_area: !input left_area
  right_area: !input right_area

  left_area_name: "{{ (left_area | default('')) | lower | replace(' ', '_') }}"
  right_area_name: "{{ (area_name(right_area) | default('')) | lower | replace(' ', '_') }}"

  enable_double_click: !input enable_double_click
  double_click_delay_ms: !input double_click_delay_ms

  left_up_1x: !input left_up_1x
  left_down_1x: !input left_down_1x
  right_up_1x: !input right_up_1x
  right_down_1x: !input right_down_1x

  left_up_2x: !input left_up_2x
  left_down_2x: !input left_down_2x
  right_up_2x: !input right_up_2x
  right_down_2x: !input right_down_2x

  any_press: !input any_press
  left_any_press: !input left_any_press
  right_any_press: !input right_any_press


trigger:
  - platform: event
    event_type: state_changed


condition:
  - condition: template
    value_template: >
      {% set d = trigger.event.data %}
      {% set eid = d.entity_id if d is not none else none %}
      {% set old = d.old_state if d is not none else none %}
      {% set new = d.new_state if d is not none else none %}
      {% set event_type = new.attributes.get('event_type') if (new is not none and new.attributes is not none) else none %}
      {{
        eid is string
        and eid.startswith('event.')
        and eid in device_event_entities
        and (old.state | string) not in ['unknown', 'unavailable']
        and (new.state | string) not in ['unknown', 'unavailable']
        and (old.state | string) != (new.state | string)
        and (event_type | string) == 'press'
      }}

action:
  - variables:
      triggered_entity_id: "{{ trigger.event.data.entity_id }}"

      # Map button id from entity_id suffix.
      #   event.<name>   -> 1
      #   event.<name>_2 -> 2
      #   event.<name>_3 -> 3
      #   event.<name>_4 -> 4
      button_id: >
        {% set eid = triggered_entity_id %}
        {% if eid.endswith('_2') %}2
        {% elif eid.endswith('_3') %}3
        {% elif eid.endswith('_4') %}4
        {% else %}1
        {% endif %}

      old_state_str: "{{ trigger.event.data.old_state.state if trigger.event.data.old_state is not none else '' }}"
      new_state_str: "{{ trigger.event.data.new_state.state if trigger.event.data.new_state is not none else '' }}"

      old_ms: >
        {% set ts = as_timestamp(old_state_str) %}
        {% if ts is number %}
          {{ (ts * 1000) | int }}
        {% else %}
          0
        {% endif %}
      new_ms: >
        {% set ts = as_timestamp(new_state_str) %}
        {% if ts is number %}
          {{ (ts * 1000) | int }}
        {% else %}
          0
        {% endif %}

      delta_ms: "{{ (new_ms - old_ms) | int }}"
      is_double: "{{ enable_double_click and delta_ms >= 1 and delta_ms <= (double_click_delay_ms | int) }}"

  - choose:
      - conditions: "{{ enable_double_click and not is_double }}"
        sequence:
          - delay:
              milliseconds: "{{ double_click_delay_ms }}"


  # Any press actions (run before per-button actions)
  - choose:
      - conditions: "{{ any_press != [] }}"
        sequence: !input any_press
      - conditions: "{{ (button_id | string) in ['1','3'] and left_any_press != [] }}"
        sequence: !input left_any_press
      - conditions: "{{ (button_id | string) in ['2','4'] and right_any_press != [] }}"
        sequence: !input right_any_press

  # Per-button actions
  - choose:
      # Left up (1)
      - conditions: "{{ (button_id | string) == '1' }}"
        sequence:
          - choose:
              # Double click: only run override if provided, otherwise do nothing (no default)
              - conditions: "{{ enable_double_click and is_double and left_up_2x != [] }}"
                sequence: !input left_up_2x
              # Single click: run override if provided, otherwise run default
              - conditions: "{{ (not enable_double_click) or (not is_double) }}"
                sequence:
                  - choose:
                      - conditions: "{{ left_up_1x != [] }}"
                        sequence: !input left_up_1x
                    default:
                      - if:
                          - condition: template
                            value_template: "{{ left_area is not none }}"
                        then:
                          - service: scene.turn_on
                            target:
                              entity_id: "scene.{{ left_area_name }}_home"
                            data:
                              transition: 1
            default: [ ]

      # Right up (2)
      - conditions: "{{ (button_id | string) == '2' }}"
        sequence:
          - choose:
              - conditions: "{{ enable_double_click and is_double and right_up_2x != [] }}"
                sequence: !input right_up_2x
              - conditions: "{{ (not enable_double_click) or (not is_double) }}"
                sequence:
                  - choose:
                      - conditions: "{{ right_up_1x != [] }}"
                        sequence: !input right_up_1x
                    default:
                      - if:
                          - condition: template
                            value_template: "{{ right_area is not none }}"
                        then:
                          - service: scene.turn_on
                            target:
                              entity_id: "scene.{{ right_area_name }}_home"
                            data:
                              transition: 1
            default: [ ]

      # Left down (3)
      - conditions: "{{ (button_id | string) == '3' }}"
        sequence:
          - choose:
              - conditions: "{{ enable_double_click and is_double and left_down_2x != [] }}"
                sequence: !input left_down_2x
              - conditions: "{{ (not enable_double_click) or (not is_double) }}"
                sequence:
                  - choose:
                      - conditions: "{{ left_down_1x != [] }}"
                        sequence: !input left_down_1x
                    default:
                      - choose:
                          - conditions: "{{ left_area is not none and (expand(area_entities(left_area)) | selectattr('domain','eq','light') | selectattr('state', 'eq', 'on') | list | count > 0) }}"
                            sequence:
                              - service: light.turn_off
                                target:
                                  area_id: "{{ left_area }}"
                                data:
                                  transition: 1
                        default:
                          - if:
                              - condition: template
                                value_template: "{{ left_area is not none }}"
                            then:
                              - service: scene.turn_on
                                target:
                                  entity_id: "scene.{{ left_area_name }}_dim"
                                data:
                                  transition: 1
            default: [ ]

      # Right down (4)
      - conditions: "{{ (button_id | string) == '4' }}"
        sequence:
          - choose:
              - conditions: "{{ enable_double_click and is_double and right_down_2x != [] }}"
                sequence: !input right_down_2x
              - conditions: "{{ (not enable_double_click) or (not is_double) }}"
                sequence:
                  - choose:
                      - conditions: "{{ right_down_1x != [] }}"
                        sequence: !input right_down_1x
                    default:
                      - choose:
                          - conditions: "{{ right_area is not none and (expand(area_entities(right_area)) | selectattr('domain','eq','light') | selectattr('state', 'eq', 'on') | list | count > 0) }}"
                            sequence:
                              - service: light.turn_off
                                target:
                                  area_id: "{{ right_area }}"
                                data:
                                  transition: 1
                        default:
                          - if:
                              - condition: template
                                value_template: "{{ right_area is not none }}"
                            then:
                              - service: scene.turn_on
                                target:
                                  entity_id: "scene.{{ right_area_name }}_dim"
                                data:
                                  transition: 1
            default: [ ]